Repository azavea/iow-boundary-tool, pull requests merged in 2022-11, with the labels that each got.

#199 Add S3 Permissions to ECS Tasks
  CHANGELOG.md
  deployment/terraform/iam.tf
Labels: Task 3.7

#202 Update Download, Replace Polygon Workflows
  CHANGELOG.md
  src/app/src/components/AfterSubmitModal.js
  src/app/src/components/DrawTools/DeletePolygonConfirmModal.js
  src/app/src/components/DrawTools/EditPolygonModal.js
  src/app/src/components/DrawTools/EditToolbar.js
  src/app/src/components/Submissions/Badges.js
  src/app/src/components/Submissions/Detail/Detail.js
  src/app/src/components/Submissions/Detail/Map.js
  src/app/src/utils.js
  src/django/api/models/boundary.py
  src/django/api/models/utility.py
  src/django/api/serializers/boundary.py
Labels: Task 3.6

#214 Add production enviroment for ecsmanage
  CHANGELOG.md
  src/django/iow/settings.py
Labels: Task 3.7

#213 Upgrading to terraform 1.1.9 and creating deployment README
  CHANGELOG.md
  deployment/README.md
  docker-compose.ci.yml
Labels: operations

#223 Fix geojson uploads
  CHANGELOG.md
  src/django/api/fields.py
Labels: Task 3.3
